server:
  port: 8084
  #forward-headers-strategy: framework
  #port: 0
springdoc:
  version: v1
  description: BBCron Teams
  api-docs:
    path: /api-docs

## Configuring info endpoint
info:
  app:
    name: BBCron Teams
    description: Handle teams in BBCron
    version: 1.0.0


spring:
  application:
    name: bbcron_teams_service
  data:
    mongodb:
      database: bbcron
      port: 27017
      host: localhost
  cloud:
    config:
      import-check:
        enabled: false

# GET ENDPOINTS
management:
  endpoints:
    web:
      exposure:
        include: mappings, info, health, metrics, loggers
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ERROR
        web:
          servlet:
            handler: INFO
